FROM node:20-alpine

WORKDIR /app

# Copia package.json e instala dependências
COPY package*.json tsconfig.json ./
RUN npm install

# Copia o resto do código (vai ser sobrescrito pelo volume em dev)
COPY . .

EXPOSE 5173

CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0", "--port", "5173"]
