FROM node:alpine

WORKDIR /app

COPY package.json package-lock.json* ./
RUN npm install

COPY .env .env

COPY . .

RUN npm run build

RUN mkdir -p /var/www/html
RUN mv dist/* /var/www/html

WORKDIR /

RUN rm -rf /app
